### ISSUE TITLE
Use a more descriptive parent module artifactId

### ISSUE THREAD

**Issue by ppalaga** [angelozerr/ec4e#13]
This is for practical reasons: When importing the source tree as Maven projects, m2e takes (by default) the project names from `<artifactId>`. I had to search in my workspace for quite long to figure out that the source tree got imported under a nondescriptive root module `parent`. Knowing that I am importing `ec4e`, I'd expect it to appear under a name that contains `ec4e`. `org.eclipse.ec4e.parent` or simply `ec4e-parent` would be good names for the parent module, IMO. I'll send a PR in short.

**Comment by angelozerr** [comment]
Yes sure!

> I'll send a PR in short.

Thanks!
