### ISSUE TITLE
Downgrade to Java 7

### ISSUE THREAD

**Issue by ppalaga** [angelozerr/ec4e#17]
The compiler level is currently at Java 8 [1]. While I personally prefer Java 8, the reality in the world of Java build tools strongly supports going back to Java 7: Both recent Maven and Gradle are still at Java 7. Note that I am saying this because I am writing an EditorConfig Maven plugin. ec4e running smoothly on Java 7 would make the users of my plugin a little bit happier ;).

I have not inspected the code too deeply to see if this is technically possible. I'd first like to ask you @angelozerr if you have some strong opinion on this? I could try to propose a PR if you give me green.

[1] https://github.com/angelozerr/ec4e/blob/dca9ea43ff9ae8f2a1625aed5d24475038776514/pom.xml#L101-L102

**Comment by angelozerr** [comment]
I'm using Stream like https://github.com/angelozerr/ec4e/blob/master/org.eclipse.ec4e.services/src/main/java/org/eclipse/ec4e/services/EditorConfigService.java#L107

But if Java8 is a bloquant things, we could support only Java7. If you find time to do that, any PR are welcome!

**Comment by ppalaga** [comment]
This is not a blocker, it just makes the area of applicability of your new parser a bit wider. Thanks, good to know that you are open to this. Let me develop my plugin without downgrading Java in ec4j first and eventually send a fix when my project gets closer to a release.

**Comment by angelozerr** [comment]
> This is not a blocker, it just makes the area of applicability of your new parser a bit wider. 

Ok I understand.

> Thanks, good to know that you are open to this. 

Thanks for you to consume ec4e parser.

> Let me develop my plugin without downgrading Java in ec4j first and eventually send a fix when my project gets closer to a release.

You mean that you will create a new project ec4j?

**Comment by ppalaga** [comment]
Closing as this was fixed in https://github.com/angelozerr/ec4j
